import type { MenuItem } from './pos-domain';
export const LEGACY_SAMPLE_MENU: MenuItem[] = [
  {
    id: 'm1',
    name: '招牌乾麵',
    price: 55,
    category: '主食',
    accent: '#ef5b2a',
    available: true,
    addon: { name: '加蛋', price: 15 },
  },
  {
    id: 'm2',
    name: '肉燥飯',
    price: 45,
    category: '主食',
    accent: '#f2a51a',
    available: true,
    addon: { name: '加蛋', price: 15 },
  },
  {
    id: 'm3',
    name: '紅油抄手',
    price: 70,
    category: '主食',
    accent: '#e84242',
    available: true,
  },
  {
    id: 'm4',
    name: '麻醬麵',
    price: 60,
    category: '主食',
    accent: '#e07b21',
    available: true,
  },
  {
    id: 'm5',
    name: '燙青菜',
    price: 45,
    category: '小菜',
    accent: '#238b57',
    available: true,
  },
  {
    id: 'm6',
    name: '滷味拼盤',
    price: 75,
    category: '小菜',
    accent: '#955b33',
    available: true,
  },
  {
    id: 'm7',
    name: '皮蛋豆腐',
    price: 50,
    category: '小菜',
    accent: '#357b78',
    available: true,
  },
  {
    id: 'm8',
    name: '黃金泡菜',
    price: 45,
    category: '小菜',
    accent: '#c79016',
    available: true,
  },
  {
    id: 'm9',
    name: '貢丸湯',
    price: 45,
    category: '湯品',
    accent: '#236b9e',
    available: true,
  },
  {
    id: 'm10',
    name: '餛飩湯',
    price: 55,
    category: '湯品',
    accent: '#5169a7',
    available: true,
  },
  {
    id: 'm11',
    name: '古早味紅茶',
    price: 30,
    category: '飲品',
    accent: '#a24c3f',
    available: true,
  },
  {
    id: 'm12',
    name: '冬瓜檸檬',
    price: 40,
    category: '飲品',
    accent: '#4e8c45',
    available: true,
  },
];
