import type { MenuItem } from './pos-domain';
/** Public original menu: https://github.com/taiwanape/Pos/blob/main/index.html
 * Verified 2026-09-08. Original sizes and prices preserved; categories added here. */
export const WUJIE_MENU: MenuItem[] = [
  {
    id: 'wujie-1',
    name: '綜合煎',
    price: 85,
    category: '煎類',
    accent: '#ef653e',
    available: true,
    addon: { name: '加蛋', price: 10 },
  },
  {
    id: 'wujie-2',
    name: '蚵仔煎',
    price: 75,
    category: '煎類',
    accent: '#ef653e',
    available: true,
    addon: { name: '加蛋', price: 10 },
  },
  {
    id: 'wujie-3',
    name: '蝦仔煎',
    price: 75,
    category: '煎類',
    accent: '#ef653e',
    available: true,
    addon: { name: '加蛋', price: 10 },
  },
  {
    id: 'wujie-4',
    name: '蛋煎',
    price: 65,
    category: '煎類',
    accent: '#ef653e',
    available: true,
    addon: { name: '加蛋', price: 10 },
  },
  {
    id: 'wujie-5',
    name: '大腸麵線(大)',
    price: 60,
    category: '麵線',
    accent: '#e8b544',
    available: true,
  },
  {
    id: 'wujie-6',
    name: '大腸麵線(小)',
    price: 50,
    category: '麵線',
    accent: '#e8b544',
    available: true,
  },
  {
    id: 'wujie-20',
    name: '清麵線(大)',
    price: 55,
    category: '麵線',
    accent: '#e8b544',
    available: true,
  },
  {
    id: 'wujie-21',
    name: '清麵線(小)',
    price: 45,
    category: '麵線',
    accent: '#e8b544',
    available: true,
  },
  {
    id: 'wujie-7',
    name: '臭豆腐',
    price: 55,
    category: '炸物',
    accent: '#b292d6',
    available: true,
  },
  {
    id: 'wujie-8',
    name: '炸餛飩',
    price: 45,
    category: '炸物',
    accent: '#b292d6',
    available: true,
  },
  {
    id: 'wujie-9',
    name: '米粉羹(大)',
    price: 40,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-10',
    name: '米粉羹(小)',
    price: 35,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-11',
    name: '餛飩麵',
    price: 45,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-12',
    name: '陽春麵',
    price: 45,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-13',
    name: '乾麵(小)',
    price: 45,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-19',
    name: '乾麵(大)',
    price: 55,
    category: '麵食',
    accent: '#9bbe7b',
    available: true,
  },
  {
    id: 'wujie-14',
    name: '魚丸湯',
    price: 45,
    category: '湯品',
    accent: '#73b2bb',
    available: true,
  },
  {
    id: 'wujie-15',
    name: '貢丸湯',
    price: 45,
    category: '湯品',
    accent: '#73b2bb',
    available: true,
  },
  {
    id: 'wujie-16',
    name: '餛飩湯',
    price: 45,
    category: '湯品',
    accent: '#73b2bb',
    available: true,
  },
  {
    id: 'wujie-17',
    name: '一串心',
    price: 20,
    category: '小點',
    accent: '#de9eae',
    available: true,
  },
  {
    id: 'wujie-18',
    name: '茶葉蛋',
    price: 15,
    category: '小點',
    accent: '#de9eae',
    available: true,
  },
];
